---
interfaces:
  Loopback0:
    address: '192.168.100.2/32'
    description: 'evpn_peer'
  Loopback1:
    address: '192.168.102.2/32'
    description: 'vtep'
  Ethernet1/21:
    address: '10.10.11.3/31'
    description: 'spine1'
  Ethernet1/22:
    address: '10.10.12.3/31'
    description: 'spine2'
  Ethernet1/23:
    address: '10.10.13.3/31'
    description: 'spine3'
  Ethernet1/24:
    address: '10.10.14.3/31'
    description: 'spine4'
bgp:
  as_number: 64500.2
  router_id: '192.168.100.2'
  neighbors:
    10.10.11.2:
      remote_as: 64500.0
      loopback: '192.168.103.1'
    10.10.12.2:
      remote_as: 64500.0
      loopback: '192.168.103.2'
    10.10.13.2:
      remote_as: 64500.0
      loopback: '192.168.103.3'
    10.10.14.2:
      remote_as: 64500.0
      loopback: '192.168.103.4'
mlag: False
vlans:
  100:
    vni: 10100
    name: 'VLAN100'
    vni_source: '192.168.100.2'
    interfaces:
      - 'Ethernet1/1'
    rd: '192.168.100.2:2'
    export_rt: '100:100'
    import_rt: '100:100'
