---
interfaces:
  Loopback0:
    address: '192.168.103.2/32'
    description: 'evpn_peer'
  Ethernet1:
    address: '10.10.12.0/31'
    description: 'leaf1'
  Ethernet2:
    address: '10.10.12.2/31'
    description: 'leaf2'
  Ethernet3:
    address: '10.10.12.4/31'
    description: 'leaf3'
  Ethernet4:
    address: '10.10.12.6/31'
    description: 'leaf4'
  Ethernet5:
    address: '10.10.12.8/31'
    description: 'leaf5'
  Ethernet6:
    address: '10.10.12.10/31'
    description: 'leaf6'
bgp:
  as_number: '64500.0'
  router_id: '192.168.103.2'
  neighbors:
    10.10.12.1:
      remote_as: '64500.1'
      loopback: '192.168.100.1'
    10.10.12.3:
      remote_as: '64500.2'
      loopback: '192.168.100.2'
    10.10.12.5:
      remote_as: '64500.3'
      send-community: true
      loopback: '192.168.100.3'
    10.10.12.7:
      remote_as: '64500.4'
      loopback: '192.168.100.4'
    10.10.12.9:
      remote_as: '64500.5'
      send-community: true
      loopback: '192.168.100.5'
    10.10.12.11:
      remote_as: '64500.5'
      loopback: '192.168.100.6'
mlag: False
